### ISSUE TITLE
[問題点]メンバー紹介リンク切れ

### ISSUE THREAD

**Issue by torippy1024** [RobohanOU/HP#28]
## 問題点
メニューバーとQ&A「どんな人たちがいますか」のメンバー紹介へのリンクが切れています。すでにメンバー紹介ページはなくなっているみたいなので、記述ごと削除した方がよいかもです。

## 改良案
index.htmlの114行と440行付近の削除

**Comment by Kappaslab** [comment]
#96ddecd
にて対応済み
